---
title: "Mixed Models Prediction"
author: "James Bury"
date: "9/5/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

if(!require(knitr)) {install.packages("knitr", repos="http://cran.us.r-project.org"); library(knitr)}
knitr::opts_chunk$set(echo = FALSE)
if(!require(dplyr)) {install.packages("dplyr", repos="http://cran.us.r-project.org"); library(dplyr)}
if(!require(tidyverse)) {install.packages("tidyverse", repos="http://cran.us.r-project.org"); library(tidyverse)}
if(!require(zoo)) {install.packages("zoo", repos="http://cran.us.r-project.org"); library(zoo)}
if(!require(data.table)) {install.packages("data.table", repos="http://cran.us.r-project.org"); library(data.table)}
if(!require(MASS)) {install.packages("MASS", repos="http://cran.us.r-project.org"); library(MASS)}
if(!require(randomForest)) {install.packages("randomForest", repos="http://cran.us.r-project.org"); library(randomForest)}
if(!require(Ckmeans.1d.dp)) {install.packages("Ckmeans.1d.dp", repos="http://cran.us.r-project.org"); library(Ckmeans.1d.dp)}
if(!require(DAAG)) {install.packages("DAAG", repos="http://cran.us.r-project.org"); library(DAAG)}
if(!require(e1071)) {install.packages("e1071", repos="http://cran.us.r-project.org"); library(e1071)}
if(!require(splines)) {install.packages("splines", repos="http://cran.us.r-project.org"); library(splines)}
if(!require(readr)) {install.packages("readr", repos="http://cran.us.r-project.org"); library(readr)}
if(!require(class)) {install.packages("class", repos="http://cran.us.r-project.org"); library(class)}
if(!require(xgboost)) {install.packages("xgboost", repos="http://cran.us.r-project.org"); library(xgboost)}
if(!require(mlr)) {install.packages("mlr", repos="http://cran.us.r-project.org"); library(mlr)}
if(!require(parallelMap)) {install.packages("parallelMap", repos="http://cran.us.r-project.org"); library(parallelMap)}
if(!require(parallel)) {install.packages("parallel", repos="http://cran.us.r-project.org"); library(parallel)}
if(!require(cluster)) {install.packages("cluster", repos="http://cran.us.r-project.org"); library(cluster)}
if(!require(factoextra)) {install.packages("factoextra", repos="http://cran.us.r-project.org"); library(factoextra)}
if(!require(gridExtra)) {install.packages("gridExtra", repos="http://cran.us.r-project.org"); library(gridExtra)}
if(!require(cluster)) {install.packages("cluster", repos="http://cran.us.r-project.org"); library(cluster)}
if(!require(mclust)) library(mclust)
library(gridExtra)
library(caret)
```

# Set up vairables
```{r cars}
train<-read.csv("scaled_train.csv")
test =read.csv("scaled_test.csv")
fix<-read.csv('fixed_effects_fixed.csv')
re<-read.csv('random_effects_fixed.csv')
```

```{r}
test = test %>% 
  dplyr::select(layup, dunk, hook, fadeaway, pullup, running, driving, reverse, fingerroll, putback, turnaround, bank, point_diff, tip, TOUCH_TIME, DRIBBLES, ratio, jump_shot, End_SC, End_PC, LOCATION, Quick_S, Clutch_T, Garbage_T, SHOT_CLOCK, SHOT_NUMBER, SHOT_RESULT2, player_name, FG_Percent, FT_Percent, FG3_Percent)

# Create Player id for test
test2 = test %>%
  dplyr::select(player_name) %>%
  unique()
test2$Player_ID = 1:nrow(test2)
test3 = inner_join(test, test2, by = c("player_name" = "player_name"))
test = test3
test = test %>%
  dplyr::select(layup, dunk, hook, fadeaway, pullup, running, driving, reverse, fingerroll, putback, turnaround, bank, point_diff, tip, TOUCH_TIME, DRIBBLES, ratio, jump_shot, End_SC, End_PC, LOCATION, Quick_S, Clutch_T, Garbage_T, SHOT_CLOCK, SHOT_NUMBER, SHOT_RESULT2, player_name, Player_ID, FG_Percent, FT_Percent, FG3_Percent)
# tmp = test$SHOT_RESULT2
# test$SHOT_RESULT2 = test$Player_ID
# test$Player_ID = tmp
# test = test %>%
#   rename(Player_ID2 = SHOT_RESULT2) %>%
#   rename(SHOT_RESULT2 = Player_ID) %>%
#   rename(Player_ID = Player_ID2)

# Are all the column names in the same order in train and test?
!(FALSE %in% (colnames(test[1:27]) == colnames(re[3:29])))
```

```{r}
re_multiply = re[,2:28]

test$Intercept = 1
test = test %>%
  dplyr::select(Intercept, everything())
test_multiply = test[,c(1:28,30)]

fixed_effects = test[,c(1,30:33)] %>%
  unique()

shot_predictions = list()

for(i in 1:nrow(re)) {
  
  # Random Effects
  player_shots = test_multiply %>% 
    filter(Player_ID == i)
  player_coefficients = re_multiply[i,]
  
  player_shot_matrix = as.matrix(player_shots[1:27])
  player_coefficients_matrix = as.vector(player_coefficients, mode = "numeric")
  prod = player_shot_matrix %*% player_coefficients_matrix
  
  # Fixed Effects
  player_fixed_effects = fixed_effects %>%
    filter(Player_ID == i)
  fixed_prod = as.vector(fix$x, mode = "numeric") %*% as.vector(player_fixed_effects[,c(1,3:5)], mode = "numeric")
  
  for(j in 1:length(prod)) {
    prod[j] = prod[j] + fixed_prod
  }
  
  # Calculate Predictions
  shot_predictions = append(shot_predictions, 1/(exp(-(prod))+1))
}
```

# Test Accuracy
```{r}
max_acc = 0

prediction = ifelse(shot_predictions >= 0.5, 1, 0)
accuracy = sum(prediction == test$SHOT_RESULT2) / nrow(test)

conf_matrix = table(prediction, test[, "SHOT_RESULT2"])
print(paste("Accuracy:", accuracy))
print(paste("Sensitivity:",sensitivity(conf_matrix)))
print(paste("Specificity:",specificity(conf_matrix)))
```